### ISSUE TITLE
Valid domain considered invalid while invalid domains accepted

### ISSUE THREAD

**Issue by fullmetalScience** [zgoat/zvalidate#1]
**_foo** should be accepted, but isn't:

    $ goatcounter db create site .. -vhost=_foo.example.org
    goatcounter: -vhost: must be a valid domain: invalid character: '_'.

**-foo** should be rejected, but isn't:

    $ goatcounter db create site .. -vhost=-foo.example.org ; echo $?
    0

**Comment by arp242** [comment]
Technically underscores are not allowed in domains, but many systems do allow it, so it's "de-facto valid".

I didn't change anything for `-foo.example.com`; according to the spec every label must start with a letter, but labels starting with an underscore are common, as are those starting with a number. Do systems currently accept labels starting with a dash? I don't know, but it's not a big deal to accept it here and I'd rather accept too much than too little. It's not intended to catch every single last possible problem, but rather people mixing up two fields, or otherwise giving wildly invalid input.
